// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezezshggzidpspqquhit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZXpzaGdnemlkcHNwcXF1aGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzIyMTYsImV4cCI6MjA2NzcwODIxNn0.JtLn8CTiXTXnvOcB1h-fddHWc37xTz-fpQBdr5sxeg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});